language: node_js
node_js:
  - "8"
python:
  - "2.7"
dist: trusty
sudo: true
git:
  depth: 1
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
  - GAE_APP_ID=cr-status
cache:
  yarn: true
  pip: true
  directories:
    - node_modules
before_install:
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash > /dev/null; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update -q
  - gcloud components install app-engine-python
  - gcloud version

install:
  - npm install -g gulp
  - npm install
  - python -m pip install --no-deps -r requirements.dev.txt
  - npm run deps
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - df -h
  - "./travis/deploy_pr_gae.sh"
  - df -h
  - export LH_MIN_PASS_SCORE=96
  - export LH_TEST_URL=https://lighthouse-ci-staging-dot-cr-status.appspot.com/features
  - node node_modules/lighthouse-ci/runlighthouse.js --score=$LH_MIN_PASS_SCORE $LH_TEST_URL
