language: node_js
node_js: '7'
dist: trusty
sudo: false
git:
  depth: 1
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
  - GAE_APP_ID=cr-status
cache:
  directories:
  - node_modules
  - travis/node_modules
install:
  - npm install -g bower gulp
  - npm install
  - npm run install-travis
script:
  - npm run lint
  - npm run build
after_success:
  - ./travis/deploy_pr_gae.sh
  - export LH_MIN_PASS_SCORE=96
  - export LH_TEST_URL=https://lighthouse-ci-staging-dot-cr-status.appspot.com/features
  - node travis/runLighthouse.js $LH_TEST_URL $LH_MIN_PASS_SCORE
