name: Continuous Integration
on:
  push:
    branches:
      - main
      - github-actions # TODO: remove
jobs:
  node_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '8.x'

      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: pre-installation
        run: |
          if [ ! -d $HOME/google-cloud-sdk/bin ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash > /dev/null; fi
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update -q
          gcloud components install app-engine-python beta
          gcloud version

      - name: installation
        run: |
          npm install -g gulp
          npm install
          npm run ci-dep

      - name: lint
        run: npm run lint

      - name: test
        run: npm run start-emulator

      - name: build
        run: npm run build

      - name: clean up
        run: df -h
